/**
 * Store layer exports.
 * Provides StorePort interface and SQLite implementation.
 *
 * @module src/store
 */

export type { Migration } from "./migrations";
// Migrations
export {
  getDbFtsTokenizer,
  getSchemaVersion,
  migrations,
  needsFtsRebuild,
  runMigrations,
} from "./migrations";

// SQLite adapter
export { SqliteAdapter } from "./sqlite";
// Types and interfaces
export type {
  ActivationIndexDocument,
  ActivationIndexIdentity,
  ActivationIndexSnapshot,
  ActivationStageName,
  ActivationStageReceipt,
  ActivationStageStatus,
  ActivationVerificationCode,
  ActivationVerificationReceipt,
  ChunkInput,
  ChunkRow,
  CleanupStats,
  CollectionRow,
  CollectionStatus,
  ContextRow,
  DocumentChangeDateDelta,
  DocumentChangeKind,
  DocumentChangeListOptions,
  DocumentChangePage,
  DocumentChangePurgeResult,
  DocumentChangeRetentionPolicy,
  DocumentChangeRetentionResult,
  DocumentChangeRow,
  DocumentChangeSet,
  DocumentChangeStructureDelta,
  DocumentInput,
  DocumentRow,
  FtsResult,
  FtsSearchOptions,
  IndexStatus,
  IngestErrorInput,
  IngestErrorRow,
  MigrationResult,
  RetrievalTraceAppendResult,
  RetrievalTraceBundle,
  RetrievalTraceBoundedBundle,
  RetrievalTraceBundleTotals,
  RetrievalTraceCursor,
  RetrievalTraceDeleteCounts,
  RetrievalTraceEventInput,
  RetrievalTraceEventKind,
  RetrievalTraceEventRow,
  RetrievalTraceExportInput,
  RetrievalTraceExportManifestInput,
  RetrievalTraceExportManifestRow,
  RetrievalTraceExportFormat,
  RetrievalTraceExportRow,
  RetrievalTraceFingerprints,
  RetrievalTraceInput,
  RetrievalTraceJudgmentInput,
  RetrievalTraceJudgmentLabel,
  RetrievalTraceJudgmentRow,
  RetrievalTraceJudgmentTargetKind,
  RetrievalTracePhysicalCleanupStatus,
  RetrievalTracePurgeResult,
  RetrievalTraceRedactionMode,
  RetrievalTraceRetentionPolicy,
  RetrievalTraceRetentionResult,
  RetrievalTraceRow,
  RetrievalTraceRunInput,
  RetrievalTraceRunKind,
  RetrievalTraceRunRow,
  RetrievalTraceStatus,
  RetrievalTraceTerminalStatus,
  RenameDocumentOptions,
  SavedCapsuleAffectedQuestionState,
  SavedCapsuleEvidenceReference,
  SavedCapsuleNotificationPreference,
  SavedCapsuleOperationStatus,
  SavedCapsuleRegistration,
  SavedCapsuleRegistrationInput,
  SavedCapsuleRegistrationRecord,
  SavedCapsuleReverificationState,
  SavedCapsuleTriggerKind,
  SavedCapsuleVerificationExpectation,
  SavedCapsuleVerificationRecord,
  StoreError,
  StoreErrorCode,
  StorePort,
  StoreResult,
} from "./types";
export { err, ok } from "./types";
