import {mock} from "bun:test";
const [source, initPath, outputPath] = process.argv.slice(2);
const attempts = {native: 0, spawn: 0, fetch: 0, dlopen: 0};
const deny = (key) => { attempts[key]++; throw new Error("CPU preflight forbids "+key); };
process.dlopen = () => deny("dlopen");
Bun.spawn = () => deny("spawn");
Bun.spawnSync = () => deny("spawn");
globalThis.fetch = () => deny("fetch");
const nativePath = Bun.resolveSync("node-llama-cpp", source+"/package.json");
const actualNative = await import(nativePath);
mock.module(nativePath, () => ({...actualNative, getLlama: () => deny("native")}));
const {SqliteAdapter} = await import(source+"/src/store/sqlite/adapter.ts");
const {captureContextEvidenceSnapshot} = await import(source+"/src/core/context-evidence.ts");
const {contextRuntimeConfigFingerprint} = await import(source+"/src/app/context-runtime-contract.ts");
const {createGnoClient} = await import(source+"/src/sdk/client.ts");
const init = await Bun.file(initPath).json();
const unwrap = (r) => {if(!r.ok) throw new Error(JSON.stringify(r.error)); return r.value;};
const store = new SqliteAdapter();
unwrap(store.openReadOnly(init.dbPath));
const before = await captureContextEvidenceSnapshot(store, "default", ["probe"]);
await store.close();
const opened = unwrap(await store.open(init.dbPath, init.config.ftsTokenizer, init.config.busyTimeoutMs));
const afterStore = await captureContextEvidenceSnapshot(store, "default", ["probe"]);
const activation = unwrap(await store.getActivationIndexSnapshot("probe"));
const document = unwrap(await store.getDocumentByUri("gno://probe/probe-0.md"));
await store.close();
const client = await createGnoClient(init);
const status = await client.status();
// Diagnostic read of real runtime fields: no replacement store/config supplied.
const effectiveConfig = client.config;
const afterSdk = await captureContextEvidenceSnapshot(client.store, "default", ["probe"]);
const sdkActivation = unwrap(await client.store.getActivationIndexSnapshot("probe"));
await client.close();
await Bun.write(outputPath, JSON.stringify({source,init,opened,attempts,before,afterStore,afterSdk,activation,sdkActivation,document,status,effectiveConfig,configFingerprint:contextRuntimeConfigFingerprint({config:effectiveConfig})},null,2));
console.log(JSON.stringify({outputPath,opened,attempts,index:afterSdk.indexFingerprint,config:contextRuntimeConfigFingerprint({config:effectiveConfig})}));
