source "https://rubygems.org"

# Ruby 3.0+ stdlib gems (removed from default)
gem "webrick"
gem "csv"
gem "base64"
gem "bigdecimal"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-optional-front-matter"
  gem "jekyll-titles-from-headings"
  gem "jekyll-relative-links"
  gem "jekyll-default-layout"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
